title: Rene Descartes, the ultimate philosopher 
author: Bozo
email: jaredm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is dedicated to Rene Descartes and all the wonderful things he said.

# social links
twitter_username: your-twitter-handle
github_username:  jaredma

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
